# Generated by Django 4.2.30 on 2026-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_delivery_fee_order_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceslab',
            name='stock',
            field=models.PositiveIntegerField(default=100, verbose_name='Stock Inventory'),
        ),
    ]
