# Generated by Django 4.2.30 on 2026-07-19 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_priceslab_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Delivery Staff'),
        ),
    ]
