# Generated by Django 4.2.30 on 2026-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_assigned_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_stock',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Bulk Stock level'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('l', 'Litre'), ('kg', 'kg'), ('g', 'g'), ('piece', 'Piece')], default='kg', max_length=10, verbose_name='Bulk Stock Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('packaged', 'Packaged Units (by Packets/Slabs)'), ('bulk', 'Bulk Stock (by Total Weight/Volume)')], default='packaged', max_length=20, verbose_name='Inventory Type'),
        ),
    ]
