# Generated by Django 4.2.30 on 2026-07-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_bulk_stock_product_bulk_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('recipient_email', models.CharField(blank=True, default='', max_length=255)),
                ('auto_daily_email', models.BooleanField(default=False)),
                ('include_orders', models.BooleanField(default=True)),
                ('include_payments', models.BooleanField(default=True)),
                ('include_inventory', models.BooleanField(default=True)),
                ('include_analytics', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
