# Generated by Django 4.2.30 on 2026-07-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_smtpconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='Delivery Rate (₹ per km)')),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Base Delivery Fee (₹)')),
                ('enable_online_payment', models.BooleanField(default=True, verbose_name='Enable Online Payment (UPI / Razorpay)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
