# Generated by Django 4.2.30 on 2026-09-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='7397536217', max_length=20, verbose_name='Store WhatsApp Phone Number')),
                ('otp_message_template', models.TextField(default='🌾 வணக்கம்! SMK மாவு கடை (SMK Flour Shop) உள்நுழைவுக்கான உங்கள் OTP எண்: {otp}. இந்த எண்ணை யாருடனும் பகிர வேண்டாம்.', verbose_name='WhatsApp OTP Message Template')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
